on: [push, pull_request]

name: security checks

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deny

      - uses: actions-rs/cargo@v1
        name: cargo deny
        with:
          command: deny
          args: check
